content: |-
  {{ .Header }}

  {{ .Inputs }}

  {{ .Outputs }}

  {{ .Providers }}

  ## Resources
  {{ range .Module.Resources }}
  - {{ .GetMode }}.{{ .Spec }} ({{ .Position.Filename }}#{{ .Position.Line }})
  {{- end }}
